### ISSUE TITLE
A little miss in package.json

### ISSUE THREAD

**Issue by dlevkov** [briebug/jest#6]
Hello Dear Briebug Team, 
You did a great job to install Jest into Angular CLI project and so painless!!!
I found a tiny 'point to improvement'.

During installation You removing all iirelevant karma+jasmine packages from package.json, but You forgot their @types:    
```
 "@types/jasmine": "~2.8.6",
 "@types/jasminewd2": "~2.0.3",
```
please remove them too, and add
```
@types/jest
```

Hope i'm helping

**Comment by dlevkov** [comment]
Also, to make it perfect, change in `tsconfig.spec.json` file: jasmine to jest

**Comment by schuchard** [comment]
Thanks @dlevkov for reporting this. We'll get a story for this in our backlog. In the meantime, feel free to submit a PR :)

In [`src/jest/index.ts:46`](https://github.com/briebug/jest-schematic/blob/master/src/jest/index.ts#L46) there are methods for adding and removing dependencies. Note they don't need versions as they're determined via npmjs.

**Comment by schuchard** [comment]
One thing I'm concerned about is removing the typing information for those using Protractor tests. Jasmine types are still needed for e2e while the unit tests need the Jest types obviously. I briefly tried configuring separate types for both without any luck.

Also I believe jest-preset-angular installs @types/jest https://github.com/thymikee/jest-preset-angular#installation but I need to confirm that works as expected.

**Comment by schuchard** [comment]
@dlevkov I think the only remaining issue you raised is the jasmine vs jest types, right? If this is causing issues for you please open a new issue briebug/jest-schematic.

We're renaming this package to @briebug/jest-schematic and archiving this repo. Thanks.
