### ISSUE TITLE
Failing to add via npm or yarn

### ISSUE THREAD

**Issue by joelmuskwe** [briebug/jest#7]
running **yarn info @briebug/jest**

returns:
`error Received invalid response from npm.
✨  Done in 3.59s.`

**Comment by schuchard** [comment]
Hi @joelmuskwe, I'm unable to reproduce your error. Are you trying to add the package or get info about it? Can you provide some additional details on how you're using the package and what you're expecting.

We I run `yarn info @briebug/jest` I see the package info...

```
➜ yarn info @briebug/jest

{ name: '@briebug/jest',
  'dist-tags':
   { latest: '1.3.0' },
  versions:
   [ '1.0.1',
     '1.1.0',
     '1.1.1',
     '1.1.2',
     '1.1.3',
     '1.2.0',
     '1.3.0' ],
  time:
   { created: '2018-06-18T20:17:01.430Z',
     '1.0.1': '2018-06-18T20:17:01.708Z',
     modified: '2018-08-14T23:04:29.423Z',
     '1.1.0': '2018-06-18T20:42:47.988Z',
     '1.1.1': '2018-06-18T21:22:25.872Z',
     '1.1.2': '2018-06-18T22:26:25.800Z',
     '1.1.3': '2018-06-18T22:44:08.517Z',
     '1.2.0': '2018-06-19T20:40:06.008Z',
     '1.3.0': '2018-06-20T18:14:19.875Z' },
  maintainers:
   [ { name: 'inorganik',
       email: 'jamie.perkins@gmail.com' },
     { name: 'jessesanders',
       email: 'jesse.sanders@briebug.com' },
     { name: 'schuchard',
       email: 'schuchard.kevin@gmail.com' } ],
  description: 'Add jest to an Angular CLI project',
  homepage: 'https://github.com/briebug/jest-schematic',
  keywords:
   [ 'schematics' ],
  repository:
   { type: 'git',
     url: 'git+https://github.com/briebug/jest-schematic.git' },
  author:
   { name: 'Briebug' },
  bugs:
   { url: 'https://github.com/briebug/jest-schematic/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '1.3.0',
  main: 'src/jest/index.js',
  scripts:
   { build: 'tsc -p tsconfig.json -watch',
     'build:once': 'tsc -p tsconfig.json',
     clean: 'git checkout HEAD -- sandbox && git clean -f -d sandbox',
     'clean:launch': 'npm run clean && npm run launch',
     launch: 'cd sandbox && ng g @briebug/jest:jest',
     test: 'npm run clean:launch && npm run test:sandbox && npm run clean',
     'test:unit': 'npm run build:once && jasmine src/**/*_spec.js',
     'test:sandbox': 'cd sandbox && npm run lint && npm run test -- --no-cache && npm run e2e && npm run build',
     link: 'cd sandbox && npm link ../',
     debug: 'echo "debug not setup with @angular/schematics\n> node --inspect-brk $(which schematics) .:addJest"',
     release: 'np' },
  schematics: './src/collection.json',
  dependencies:
   { '@angular-devkit/core': '^0.6.8',
     '@angular-devkit/schematics': '^0.6.8',
     '@schematics/angular': '^0.6.8',
     rxjs: '^6.2.1' },
  publishConfig:
   { access: 'public' },
  devDependencies:
   { '@types/jasmine': '^2.6.0',
     '@types/node': '^8.0.31',
     jasmine: '^2.8.0',
     typescript: '^2.9.1',
     np: '^3.0.4' },
  gitHead: 'd1547f543fce42399f794eecf64c48f60eabfdda',
  dist:
   { integrity: 'sha512-wNTZPZJGepQyM5KB64ZXsFQpMilDtGIHXVYWAfr+3Br+wWeedc3iyRFXFPeiSHxGaZCE3t5uyes7OAXxrc5C2g==',
     shasum: '58baf09be8f3c624827e978867c1373486d942ce',
     tarball: 'https://registry.npmjs.org/@briebug/jest/-/jest-1.3.0.tgz',
     fileCount: 28,
     unpackedSize: 55959,
     'npm-signature': '-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.4\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJbKpl8CRA9TVsSAnZWagAAywcP/2Ne+nMHGVoKZB8T371i\nWYpd+SeVC4vxwJHr0QtZpJELVdxIg4yX1QS0C6Kkuuy0E0kJbXybFr4JFzt3\nxpn1z2DaQhcOlyUI0gNYCljsgWKnQfZaBm3+QLCw9nx90qdy7Sz9eVVA/9bv\n5+OcWiNxArcoxrvg4+CHAXec6C80wm/bQszQDZhqrQagO/ig8odXPg2/Repw\n/E1ONp4O0ii3eNBOQlAjVppZ9QaUKdNyAF4Qn7lH/4nqOMsPI6UwyBiDzp41\n2k7Eb6NpnS7DZdfRhB7pzo6i5kcTqb+HyjYrufNWKb9X5r42DHyYxqOGz/Vy\nGA6YyMdM9fA5Zcx2VLPOpgbXfFurq+4xor2tO+bJwJ1+cue4pHoMlPCM7pHP\nQVvqa+ggMAvKxlrodji37dPaPKMA4Lc+q/Aj/TL4j8TSSiu8SMsoYonqQeFd\nYtqd5lJmT73jYPJvZMpN8o3KPDTtngKM1fMTb55+cnYreY2/dPxZesrsCE2q\n7ilgckjQbdtooAKs00/CRW0yKR87BIoB79mkzA7QKwT5lEffC8yq588SPmO0\neLf//bu2HcKaNJhEwmVoZEaFjeMhBRjA7z0VloyHaceBCQlKP4azjvLjGFM7\nLjmkULH9OGlwSGR//ouiyF3uhyeodpJtr2a5b4HjcsiaXUQcHsy6/lTrG+oA\nmtEZ\r\n=AEHX\r\n-----END PGP SIGNATURE-----\r\n' },
  directories: {} }
```

and `npm info @brieubg/jest` returns 

```
➜ npm info @briebug/jest

@briebug/jest@1.3.0 | MIT | deps: 4 | versions: 7
Add jest to an Angular CLI project
https://github.com/briebug/jest-schematic

keywords: schematics

dist
.tarball https://registry.npmjs.org/@briebug/jest/-/jest-1.3.0.tgz
.shasum: 58baf09be8f3c624827e978867c1373486d942ce
.integrity: sha512-wNTZPZJGepQyM5KB64ZXsFQpMilDtGIHXVYWAfr+3Br+wWeedc3iyRFXFPeiSHxGaZCE3t5uyes7OAXxrc5C2g==
.unpackedSize: 56.0 kB

dependencies:
@angular-devkit/core: ^0.6.8       @schematics/angular: ^0.6.8
@angular-devkit/schematics: ^0.6.8 rxjs: ^6.2.1

maintainers:
- jrista <jon.rista@briebug.com>
- blove <brian@brianflove.com>
- inorganik <jamie.perkins@gmail.com>
- schuchard <schuchard.kevin@gmail.com>
- jessesanders <jesse.sanders@briebug.com>

dist-tags:
latest: 1.3.0

published 2 months ago by schuchard <schuchard.kevin@gmail.com>
```

**Comment by joelmuskwe** [comment]
Please find below screenshot of errors i am getting both yarn and npm.

node -v = v8.11.3
npm -v = 5.6.0
yarn --version = 1.9.4

<img width="1286" alt="screen shot 2018-08-22 at 18 53 29" src="https://user-images.githubusercontent.com/5989937/44478192-2e9c2100-a63d-11e8-8075-c6287215e8d3.png">


error log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@8/8.11.3_1/bin/node',
1 verbose cli   '/usr/local/opt/node@8/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@briebug/jest' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose npm-session a8c5bdd0dd0a9032
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@briebug%2fjest 3001ms
8 silly fetchPackageMetaData error for @briebug/jest@latest 404 Not Found: @briebug/jest@latest
9 verbose stack Error: 404 Not Found: @briebug/jest@latest
9 verbose stack     at fetch.then.res (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:810:20)
9 verbose stack     at tryOnImmediate (timers.js:768:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
10 verbose cwd /Users/joelmuskwe/Joel/projects/examples/briebug-demo
11 verbose Darwin 17.7.0
12 verbose argv "/usr/local/Cellar/node@8/8.11.3_1/bin/node" "/usr/local/opt/node@8/bin/npm" "install" "-g" "@briebug/jest"
13 verbose node v8.11.3
14 verbose npm  v5.6.0
15 error code E404
16 error 404 Not Found: @briebug/jest@latest
17 verbose exit [ 1, true ]

**Comment by schuchard** [comment]
can you try a few things.

- in your browser can you visit the url listed in the debug log on line 7? Does it return JSON?
  - https://registry.npmjs.org/@briebug%2fjest
  - https://registry.yarnpkg.com/@briebug%2fjest
- in your terminal, do either of the following return JSON for the packages
  - `curl https://registry.yarnpkg.com/@briebug%2fjest`
  - `curl https://registry.yarnpkg.com/@angular%2fcli`

**Comment by joelmuskwe** [comment]
i managed to get the npm install -g @briebug/jest to work seems it doesn't like to be installed when someone is logged in to their npm accounts. i logged out and it installed but for yarn it returned the following:

➜  briebug-demo git:(master) ✗ yarn global add @briebug/jest
yarn global v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > rxjs-tslint@0.1.5" has unmet peer dependency "tslint@^5.0.0".
[4/4] 📃  Building fresh packages...
warning "@briebug/jest@1.3.0" has no binaries
✨  Done in 7.93s.



Also then ran ng g @briebug/jest:jest:

got the following error:
➜  briebug-demo git:(master) ✗ ng g @briebug/jest:jest
Could not find module "@briebug/jest" from "/Users/joelmuskwe/Joel/projects/examples/briebug-demo".
Error: Could not find module "@briebug/jest" from "/Users/joelmuskwe/Joel/projects/examples/briebug-demo".
    at Object.resolve (/Users/joelmuskwe/Joel/projects/examples/briebug-demo/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at NodeModulesEngineHost._resolvePackageJson (/Users/joelmuskwe/Joel/projects/examples/briebug-demo/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:28:21)
    at NodeModulesEngineHost._resolveCollectionPath (/Users/joelmuskwe/Joel/projects/examples/briebug-demo/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:69:40)
    at NodeModulesEngineHost.createCollectionDescription (/Users/joelmuskwe/Joel/projects/examples/briebug-demo/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:106:27)
    at SchematicEngine._createCollectionDescription (/Users/joelmuskwe/Joel/projects/examples/briebug-demo/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/Users/joelmuskwe/Joel/projects/examples/briebug-demo/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at Object.getCollection (/Users/joelmuskwe/Joel/projects/examples/briebug-demo/node_modules/@angular/cli/utilities/schematics.js:35:31)
    at GenerateCommand.getOptions (/Users/joelmuskwe/Joel/projects/examples/briebug-demo/node_modules/@angular/cli/models/schematic-command.js:215:41)
    at GenerateCommand.<anonymous> (/Users/joelmuskwe/Joel/projects/examples/briebug-demo/node_modules/@angular/cli/commands/generate.js:45:53)
    at Generator.next (<anonymous>)
➜  briebug-demo git:(master) ✗

**My Enviroment**
Angular CLI: 6.1.4
Node: 8.11.3
OS: darwin x64
Angular: 6.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.4
@angular-devkit/build-angular     0.7.4
@angular-devkit/build-optimizer   0.7.4
@angular-devkit/build-webpack     0.7.4
@angular-devkit/core              0.7.4
@angular-devkit/schematics        0.7.4
@angular/cli                      6.1.4
@ngtools/webpack                  6.1.4
@schematics/angular               0.7.4
@schematics/update                0.7.4
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2

**Comment by schuchard** [comment]
@joelmuskwe - any changes on this issue? I'm still unable to reproduce. Regarding your last comment
>  npm install -g @briebug/jest to work seems it doesn't like to be installed when someone is logged in to their npm accounts. 

I'm logged in and still unable to reproduce, yarn is working as well. We're renaming this package and archiving this repo. If the problem still persists or you have any new discoveries. Please open a new issue at https://github.com/briebug/jest-schematic. Thanks
