### ISSUE TITLE
"SyntaxError: Unexpected token import" when running tests on a new project

### ISSUE THREAD

**Issue by pevel** [briebug/jest#8]
This bug can be fixed manually. Anyways I guess it would be nice if the schematics worked out of the box.

**Describe the bug**
"SyntaxError: Unexpected token import" error pops out after I try to run tests on a newly created Angular app. 

**To Reproduce**
1. Create a new Angular app using Angular CLI.
2. Run the jest-schematic with `ng add @briebug/jest`
3. See output with error:

```
 FAIL  src/app/app.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\projects\ng-jest-test\src\setup-jest.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import 'jest-preset-angular';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.656s
```

**Expected behavior**
Tests compile and run correctly after applying jest-schematics on a new Angular project.

**Desktop:**
 - OS: Windows 10
 - Jest-schematic: 1.3.0
 - Jest: 23.5.0
 - Angular: 6.1.4
 - Angular CLI: 6.1.5

**Additional context**
The bug is loosely connected with this one: https://github.com/thymikee/jest-preset-angular/issues/4
Modifying test TS config (default: tsconfig.spec.json) manually solves the issue in my case. "module" in "compilerOptions" needs to changed to "commonjs".

**Comment by blove** [comment]
Hey @pevel I was not able to reproduce the issue. I checked, and the src/tsconfig.spec.ts file already has the `compilerOptions.module` property set to "commonjs" after creating a new project.

Here's my ng -v:

```
Angular CLI: 6.0.8
Node: 8.11.1
OS: darwin x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.3.0
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by pevel** [comment]
To reproduce the issue, you'd need to update your Angular CLI. I used 6.1.5 as mentioned in the original post. I re-confirmed that 6.1.5 doesn't add compilerOptions.module option. The question is whether it should be considered Angular CLI issue or Jest-schematic issue. What's your opinion on this?
